const changeStore=(key,fallback=[])=>JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));
const saveChangeStore=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const changeStamp=()=>new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date());
const safeText=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
let companyUpdateRequests=changeStore('idi-company-update-requests',[
  {id:'CUR-260701',company:'Mekong AgriTech',requester:'Maly Sok',email:'maly@mekongagri.com',changes:'Update the product list and replace the main contact number.',reason:'We launched a new soil sensor kit and changed our sales hotline.',status:'Pending',submitted:'1 Jul 2026, 10:15'}
]);
let companyAuditEntries=changeStore('idi-company-audit-log',[
  {company:'Koompi Digital',actor:'Dara Vong',email:'directory@idiapp.org',source:'Approved owner request CUR-260625',reason:'Updated verified website and product catalog after evidence review.',when:'30 Jun 2026, 16:42'}
]);
let membershipUpdateRequests=changeStore('idi-membership-update-requests',[
  {id:'MUR-260629',member:'Dara Lim',email:'dara@sabaylogistics.com',tier:'Premium',organization:'Sabay Logistics',changes:'Upgrade membership and update job title.',reason:'Company requires access to funding-request tools.',status:'Pending',submitted:'29 Jun 2026, 14:20'}
]);
let membershipAuditEntries=changeStore('idi-membership-audit-log',[
  {member:'Vattanac R.',actor:'Sophea Chan',email:'membership@idiapp.org',source:'Approved request MUR-260621',reason:'Updated organization role after supporting document review.',when:'27 Jun 2026, 09:30'}
]);

document.body.insertAdjacentHTML('beforeend',`
  <div class="modal-backdrop" id="companyChangeModal" aria-hidden="true"><div class="modal workflow-modal"><button class="modal-close" data-company-change-close>×</button><div class="modal-title"><span class="stat-icon purple">▦</span><div><h2 id="companyChangeTitle">Request company update</h2><p id="companyChangeSubtitle">Verified information stays locked until an administrator approves the request.</p></div></div><form id="companyChangeForm"><input type="hidden" name="mode"><input type="hidden" name="requestId"><label>Company<input name="company" readonly required></label><div class="form-row"><label>Business category<input name="industry" required></label><label>Location<input name="location" required></label></div><label>Company description<textarea name="description" required></textarea></label><label id="companyChangeSourceLabel">Change source<select name="source"><option>Approved owner request</option><option>Direct admin correction</option><option>Compliance review</option><option>Annual verification review</option></select></label><label>Reason / administrator note<textarea name="reason" required placeholder="Explain what is changing, why it is necessary, and the evidence reviewed."></textarea></label><div class="record-lock-note"><span>🔒</span><div><strong>Verified-record control</strong><br>Owners submit requests only. An administrator must review and save any public change.</div></div><div class="modal-actions"><button type="button" class="secondary" data-company-change-close>Cancel</button><button type="submit" class="primary" id="companyChangeSubmit">Submit update request</button></div></form></div></div>
  <div class="modal-backdrop" id="membershipChangeModal" aria-hidden="true"><div class="modal workflow-modal"><button class="modal-close" data-membership-change-close>×</button><div class="modal-title"><span class="stat-icon blue">♙</span><div><h2 id="membershipChangeTitle">Request membership update</h2><p>Every member may request changes. Admin approval and an audit note are required.</p></div></div><form id="membershipChangeForm"><input type="hidden" name="mode"><label>Member email<input name="email" type="email" readonly required></label><div class="form-row"><label>Requested membership<select name="tier"><option>VIP</option><option>Premium</option><option>Standard</option><option>Guest</option></select></label><label>Organization<input name="organization" required></label></div><label>Requested changes<textarea name="changes" required placeholder="Contact details, organization, representative, tier, or other membership information"></textarea></label><label>Reason / admin note<textarea name="reason" required placeholder="Explain the request or administrative reason for this update"></textarea></label><div class="modal-actions"><button type="button" class="secondary" data-membership-change-close>Cancel</button><button type="submit" class="primary" id="membershipChangeSubmit">Submit membership request</button></div></form></div></div>`);

const companyChangeModal=document.getElementById('companyChangeModal');
const membershipChangeModal=document.getElementById('membershipChangeModal');
document.querySelectorAll('[data-company-change-close]').forEach(button=>button.onclick=()=>companyChangeModal.classList.remove('open'));
document.querySelectorAll('[data-membership-change-close]').forEach(button=>button.onclick=()=>membershipChangeModal.classList.remove('open'));

function openCompanyChange(companyName,mode='request',requestId=''){
  const company=companies.find(item=>item.name===companyName);if(!company)return;
  const form=document.getElementById('companyChangeForm');form.elements.mode.value=mode;form.elements.requestId.value=requestId;form.elements.company.value=company.name;form.elements.industry.value=company.industry;form.elements.location.value=company.location;form.elements.description.value=company.desc;form.elements.reason.value='';
  const admin=mode==='admin';document.getElementById('companyChangeTitle').textContent=admin?'Admin company update':'Request company profile update';document.getElementById('companyChangeSubtitle').textContent=admin?'Save a controlled change with staff identity, source, timestamp, and reason.':'This verified record is locked. Submit the requested change and reason for admin review.';document.getElementById('companyChangeSourceLabel').style.display=admin?'':'none';document.getElementById('companyChangeSubmit').textContent=admin?'Save verified change':'Submit update request';companyChangeModal.classList.add('open');companyChangeModal.setAttribute('aria-hidden','false');
}
function openMembershipChange(email=currentMember?.email,mode='request'){
  const member=members.find(item=>item.email===email)||{email,tier:currentMember?.tier||'Standard',org:currentMember?.organization||'Individual'};const form=document.getElementById('membershipChangeForm');form.elements.mode.value=mode;form.elements.email.value=member.email;form.elements.tier.value=member.tier;form.elements.organization.value=member.org;form.elements.changes.value='';form.elements.reason.value='';const admin=mode==='admin';document.getElementById('membershipChangeTitle').textContent=admin?'Admin membership update':'Request membership update';document.getElementById('membershipChangeSubmit').textContent=admin?'Save membership change':'Submit membership request';membershipChangeModal.classList.add('open');membershipChangeModal.setAttribute('aria-hidden','false');
}

function renderCompanyChangeControl(){
  const requestHost=document.getElementById('companyChangeRequests'),auditHost=document.getElementById('companyAuditLog');if(!requestHost||!auditHost)return;
  requestHost.innerHTML=companyUpdateRequests.map(request=>`<article class="change-request"><header><div><h3>${safeText(request.company)}</h3><small>${safeText(request.id)} • ${safeText(request.requester)} • ${safeText(request.submitted)}</small></div><span class="request-status ${request.status.toLowerCase()}">${safeText(request.status)}</span></header><p><strong>Requested:</strong> ${safeText(request.changes)}</p><p><strong>Reason:</strong> ${safeText(request.reason)}</p>${request.status==='Pending'?`<label>Admin review note<textarea data-company-review-note="${request.id}" placeholder="Required for update or rejection"></textarea></label><div class="request-actions"><button class="primary" data-company-review="${request.id}">Review & update</button><button class="secondary" data-company-reject="${request.id}">Reject request</button></div>`:''}</article>`).join('')||'<p>No company update requests.</p>';
  auditHost.innerHTML=companyAuditEntries.map(entry=>`<article class="audit-entry"><header><div><h3>${safeText(entry.company)}</h3><small>${safeText(entry.when)}</small></div><span class="request-status approved">Logged</span></header><p><strong>${safeText(entry.actor)}</strong> • ${safeText(entry.email)}</p><p><strong>Source:</strong> ${safeText(entry.source)}</p><p><strong>Note:</strong> ${safeText(entry.reason)}</p></article>`).join('')||'<p>No company changes logged.</p>';
  document.querySelectorAll('[data-company-review]').forEach(button=>button.onclick=()=>{const request=companyUpdateRequests.find(item=>item.id===button.dataset.companyReview),note=document.querySelector(`[data-company-review-note="${request.id}"]`).value.trim();if(!note){showToast('Admin note required','Explain the evidence reviewed before changing verified information.');return}openCompanyChange(request.company,'admin',request.id);document.getElementById('companyChangeForm').elements.reason.value=note});
  document.querySelectorAll('[data-company-reject]').forEach(button=>button.onclick=()=>{const request=companyUpdateRequests.find(item=>item.id===button.dataset.companyReject),note=document.querySelector(`[data-company-review-note="${request.id}"]`).value.trim();if(!note){showToast('Admin note required','Add a reason before rejecting this request.');return}request.status='Rejected';companyAuditEntries.unshift({company:request.company,actor:currentMember?.name||'Administrator',email:currentMember?.email||'admin@idiapp.org',source:`Rejected owner request ${request.id}`,reason:note,when:changeStamp()});saveChangeStore('idi-company-update-requests',companyUpdateRequests);saveChangeStore('idi-company-audit-log',companyAuditEntries);renderCompanyChangeControl();showToast('Request rejected','The owner can see the administrator note and submit a new request.')});
}

function installMembershipControl(){
  const page=document.getElementById('page-memberships');if(!page||document.getElementById('membershipChangeRequests'))return;page.insertAdjacentHTML('beforeend',`<section class="admin-change-control change-control-grid"><article class="panel"><div class="panel-head"><div><h2>Membership update requests</h2><p>Requests from all membership types</p></div></div><div class="change-request-list" id="membershipChangeRequests"></div></article><article class="panel"><div class="panel-head"><div><h2>Membership audit log</h2><p>Staff, source, reason, and timestamp</p></div></div><div class="audit-log-list" id="membershipAuditLog"></div></article></section>`);
}
function renderMembershipChangeControl(){
  const requestHost=document.getElementById('membershipChangeRequests'),auditHost=document.getElementById('membershipAuditLog');if(!requestHost||!auditHost)return;
  requestHost.innerHTML=membershipUpdateRequests.map(request=>`<article class="change-request"><header><div><h3>${safeText(request.member)}</h3><small>${safeText(request.id)} • ${safeText(request.email)} • ${safeText(request.submitted)}</small></div><span class="request-status ${request.status.toLowerCase()}">${safeText(request.status)}</span></header><p><strong>Request:</strong> ${safeText(request.changes)}</p><p><strong>Requested tier:</strong> ${safeText(request.tier)} • <strong>Reason:</strong> ${safeText(request.reason)}</p>${request.status==='Pending'?`<label>Admin decision note<textarea data-member-review-note="${request.id}" placeholder="Required for approval or rejection"></textarea></label><div class="request-actions"><button class="primary" data-member-approve="${request.id}">Approve update</button><button class="secondary" data-member-reject="${request.id}">Reject</button></div>`:''}</article>`).join('')||'<p>No membership update requests.</p>';
  auditHost.innerHTML=membershipAuditEntries.map(entry=>`<article class="audit-entry"><header><div><h3>${safeText(entry.member)}</h3><small>${safeText(entry.when)}</small></div><span class="request-status approved">Logged</span></header><p><strong>${safeText(entry.actor)}</strong> • ${safeText(entry.email)}</p><p><strong>Source:</strong> ${safeText(entry.source)}</p><p><strong>Note:</strong> ${safeText(entry.reason)}</p></article>`).join('')||'<p>No membership changes logged.</p>';
  document.querySelectorAll('[data-member-approve],[data-member-reject]').forEach(button=>button.onclick=()=>{const id=button.dataset.memberApprove||button.dataset.memberReject,request=membershipUpdateRequests.find(item=>item.id===id),note=document.querySelector(`[data-member-review-note="${id}"]`).value.trim();if(!note){showToast('Admin note required','Record why this membership request is approved or rejected.');return}const approved=!!button.dataset.memberApprove;request.status=approved?'Approved':'Rejected';if(approved){const member=members.find(item=>item.email===request.email);if(member){member.tier=request.tier;member.org=request.organization}}membershipAuditEntries.unshift({member:request.member,actor:currentMember?.name||'Administrator',email:currentMember?.email||'admin@idiapp.org',source:`${approved?'Approved':'Rejected'} request ${id}`,reason:note,when:changeStamp()});saveChangeStore('idi-membership-update-requests',membershipUpdateRequests);saveChangeStore('idi-membership-audit-log',membershipAuditEntries);renderMembers();renderMembershipChangeControl();showToast(`Request ${approved?'approved':'rejected'}`,approved?'Membership information was updated and logged.':'The member can review the note and submit again.')});
}

document.getElementById('companyChangeForm').onsubmit=event=>{event.preventDefault();const form=new FormData(event.target),company=companies.find(item=>item.name===form.get('company')),admin=form.get('mode')==='admin';if(admin){company.industry=form.get('industry');company.location=form.get('location');company.desc=form.get('description');const requestId=String(form.get('requestId')||'');if(requestId){const request=companyUpdateRequests.find(item=>item.id===requestId);if(request)request.status='Approved'}companyAuditEntries.unshift({company:company.name,actor:currentMember?.name||'Administrator',email:currentMember?.email||'admin@idiapp.org',source:requestId?`Approved owner request ${requestId}`:form.get('source'),reason:form.get('reason'),when:changeStamp()});saveChangeStore('idi-company-update-requests',companyUpdateRequests);saveChangeStore('idi-company-audit-log',companyAuditEntries);companyChangeModal.classList.remove('open');renderDirectory();renderPublicDirectory();renderCompanyChangeControl();showToast('Verified company updated','The change and administrator note were added to the audit log.')}else{const id=`CUR-${String(Date.now()).slice(-6)}`;companyUpdateRequests.unshift({id,company:company.name,requester:currentMember?.name||'Company owner',email:currentMember?.email||'',changes:`Category: ${form.get('industry')}; location: ${form.get('location')}; description update requested.`,reason:form.get('reason'),status:'Pending',submitted:changeStamp()});saveChangeStore('idi-company-update-requests',companyUpdateRequests);companyChangeModal.classList.remove('open');renderCompanyChangeControl();showToast('Update request submitted',`${id} is waiting for administrator review.`)}};

document.getElementById('membershipChangeForm').onsubmit=event=>{event.preventDefault();const form=new FormData(event.target),member=members.find(item=>item.email===form.get('email')),admin=form.get('mode')==='admin';if(admin){if(member){member.tier=form.get('tier');member.org=form.get('organization')}membershipAuditEntries.unshift({member:member?.name||form.get('email'),actor:currentMember?.name||'Administrator',email:currentMember?.email||'admin@idiapp.org',source:'Direct admin correction',reason:form.get('reason'),when:changeStamp()});saveChangeStore('idi-membership-audit-log',membershipAuditEntries);showToast('Membership updated','The staff identity, reason, and timestamp were logged.')}else{const id=`MUR-${String(Date.now()).slice(-6)}`;membershipUpdateRequests.unshift({id,member:currentMember?.name||member?.name||'Member',email:form.get('email'),tier:form.get('tier'),organization:form.get('organization'),changes:form.get('changes'),reason:form.get('reason'),status:'Pending',submitted:changeStamp()});saveChangeStore('idi-membership-update-requests',membershipUpdateRequests);showToast('Membership request submitted',`${id} is awaiting administrator approval.`)}membershipChangeModal.classList.remove('open');renderMembers();renderMembershipChangeControl()};

const governedCompanyProfile=openCompanyProfile;
openCompanyProfile=function(name){governedCompanyProfile(name);const company=companies.find(item=>item.name===name),side=document.querySelector('#companyProfileContent .profile-side');if(!company||!side)return;const owner=!!currentMember&&(currentMember.organization===company.name||currentMember.email===company.ownerEmail);let action='';if(currentMember?.isAdmin)action='<button class="primary profile-admin-edit">Edit verified information</button>';else if(owner)action='<button class="secondary profile-owner-request">Request profile update</button>';side.insertAdjacentHTML('beforeend',`<div class="record-lock-note"><span>🔒</span><div><strong>${isCompanyVerified(company)?'Verified profile locked':'Profile under review'}</strong><br>${isCompanyVerified(company)?'The owner must request changes. Only an administrator can update the public record.':'Information may be completed before final verification.'}</div></div><div class="profile-change-actions">${action}</div>`);side.querySelector('.profile-admin-edit')?.addEventListener('click',()=>openCompanyChange(company.name,'admin'));side.querySelector('.profile-owner-request')?.addEventListener('click',()=>openCompanyChange(company.name,'request'))};

const governedRenderMembers=renderMembers;
renderMembers=function(){governedRenderMembers();document.querySelectorAll('[data-member-manage]').forEach(button=>button.onclick=()=>openMembershipChange(button.dataset.memberManage,'admin'))};

const billingHead=document.querySelector('#page-billing .page-head');if(billingHead){const button=document.createElement('button');button.className='secondary member-update-request';button.textContent='Request membership update';button.onclick=()=>openMembershipChange(currentMember?.email,'request');billingHead.append(button)}

const partnerForm=document.getElementById('partnerOnboardingForm');
const partnerOrganizationSection=partnerForm.querySelector('.workflow-section');
partnerOrganizationSection.querySelector('h3').insertAdjacentHTML('afterend','<label class="partner-logo-upload"><span>LOGO</span><div><strong>Organization logo *</strong><input name="logo" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" required><small>Required for every VC and Strategic Partner profile</small></div></label>');
const generatedPartnerLogo=partner=>generatedCompanyLogo({name:partner.name,industry:partner.type,color:partner.color});
function ensurePartnerLogos(){partnerOrganizations.forEach(partner=>{if(!partner.logo)partner.logo=generatedPartnerLogo(partner)})}
ensurePartnerLogos();
function partnerLogoMarkup(partner,cls){if(!partner.logo)partner.logo=generatedPartnerLogo(partner);return `<img class="${cls} has-image" src="${partner.logo}" alt="${safeText(partner.name)} logo" loading="lazy">`}
renderPartners=function(){const q=document.getElementById('partnerSearch').value.toLowerCase(),type=document.getElementById('partnerType').value,sector=document.getElementById('partnerSector').value,rows=partnerOrganizations.filter(p=>(p.name+p.focus+p.capability+p.sectors.join(' ')).toLowerCase().includes(q)&&(type==='all'||p.type===type)&&(sector==='all'||p.sectors.includes(sector)));document.getElementById('partnerGrid').innerHTML=rows.map(p=>`<article class="partner-card"><div class="partner-top">${partnerLogoMarkup(p,'partner-logo')}<div><h3>${p.name}</h3><p>${p.type} • ${p.location}</p></div>${p.verified===false?'<span class="status potential">Pending verification</span>':'<span class="verified">●</span>'}</div><p class="partner-focus">${p.focus}</p><div class="tags">${p.sectors.map(s=>`<span class="tag">${s}</span>`).join('')}</div><div class="partner-facts"><div><span>Investment / Value</span><strong>${p.ticket}</strong></div><div><span>Preferred stage</span><strong>${p.stage}</strong></div><div><span>Core capability</span><strong>${p.capability}</strong></div></div><div class="partner-actions"><button class="secondary campaign-create" data-name="${p.name}">Create campaign</button><button class="primary meeting-request" data-name="${p.name}">Request meeting</button></div></article>`).join('')||'<p>No organizations match these filters.</p>';document.querySelectorAll('.meeting-request').forEach(button=>button.onclick=()=>showToast('Meeting request created',`${button.dataset.name} will receive an in-app and email notification.`));document.querySelectorAll('.campaign-create').forEach(button=>button.onclick=()=>openCampaignModal(button.dataset.name))};
renderPublicPartners=function(){const rows=partnerOrganizations.filter(partner=>partner.verified!==false&&(activePublicPartnerFilter==='all'||partner.type===activePublicPartnerFilter));document.getElementById('publicPartnerGrid').innerHTML=rows.map(partner=>{const index=partnerOrganizations.indexOf(partner);return `<article class="public-partner-card"><div class="public-partner-head">${partnerLogoMarkup(partner,'public-partner-logo')}<div><h3>${partner.name}</h3><p>${partner.type} • ${partner.location}</p></div><span class="public-partner-verified">●</span></div><p class="public-partner-focus">${partner.focus}</p><div class="tags">${partner.sectors.map(sector=>`<span class="tag">${sector}</span>`).join('')}</div><div class="public-partner-facts"><div><span>Investment / value</span><strong>${partner.ticket}</strong></div><div><span>Preferred stage</span><strong>${partner.stage}</strong></div><div><span>Core capability</span><strong>${partner.capability}</strong></div></div><button class="secondary public-partner-button" data-public-partner="${index}">View organization →</button></article>`}).join('');document.getElementById('publicPartnerCount').textContent=`Showing ${rows.length} verified ${activePublicPartnerFilter==='all'?'capital and strategic partners':activePublicPartnerFilter.toLowerCase()+' organizations'}`;document.querySelectorAll('[data-public-partner]').forEach(button=>button.onclick=()=>openPublicPartner(Number(button.dataset.publicPartner)))};
const governedOpenPublicPartner=openPublicPartner;openPublicPartner=function(index){governedOpenPublicPartner(index);const partner=partnerOrganizations[index],logo=document.querySelector('.public-partner-profile-logo');if(partner&&logo){logo.textContent='';logo.style.backgroundImage=`url('${partner.logo}')`}};
partnerForm.onsubmit=event=>{event.preventDefault();const form=new FormData(event.target),file=form.get('logo'),sectors=String(form.get('sectors')).split(',').map(value=>value.trim()).filter(Boolean),partner={name:form.get('name'),type:form.get('type'),location:form.get('location'),sectors,focus:form.get('focus'),ticket:form.get('ticket'),stage:form.get('stage'),capability:form.get('capability'),website:form.get('website'),contact:form.get('contact'),email:form.get('email'),color:'#173f96',verified:false};partner.logo=file&&file.size?URL.createObjectURL(file):generatedPartnerLogo(partner);partnerOrganizations.unshift(partner);ensurePartnerLogos();renderPartners();renderPublicPartners();closePartnerOnboarding();showToast('Partner profile submitted',`${partner.name} and its logo are pending verification.`);event.target.reset()};

installMembershipControl();renderCompanyChangeControl();renderMembershipChangeControl();renderPartners();renderPublicPartners();renderMembers();
