const platformPageItems=[
  ['profile','♙','My Profile & Company','Account, verification and company information'],
  ['notifications','♢','Notification Center','News, invitations, renewals and preferences'],
  ['public-pages','▧','All Page Management','Edit all website, app, content and admin related pages'],
  ['approvals','✓','Approvals & Verification','Administrative review queues'],
  ['registrations','◷','Event Registrations','Attendees, invitations and check-in']
];
platformPageItems.forEach(item=>{if(!systemPageCatalog.some(row=>row[0]===item[0]))systemPageCatalog.push(item)});
Object.values(loginProfiles).forEach(profile=>['profile','notifications'].forEach(page=>{if(!profile.allowed.includes(page))profile.allowed.push(page)}));
['public-pages','approvals','registrations'].forEach(page=>{if(!loginProfiles.admin.allowed.includes(page))loginProfiles.admin.allowed.push(page)});

const workspaceNav=document.querySelectorAll('#sidebar nav')[1];
workspaceNav.insertAdjacentHTML('afterbegin',`<button class="nav-item" data-page="profile"><span>♙</span> My Profile & Company</button><button class="nav-item" data-page="notifications"><span>♢</span> Notification Center <em id="notificationNavCount">4</em></button>`);
workspaceNav.insertAdjacentHTML('beforeend',`<button class="nav-item admin-only-nav" data-page="public-pages"><span>▧</span> All Pages</button><button class="nav-item admin-only-nav active" data-page="approvals"><span>✓</span> Approvals & Verification <em>9</em></button><button class="nav-item admin-only-nav" data-page="registrations"><span>◷</span> Event Registrations</button>`);
document.querySelectorAll('[data-page="profile"],[data-page="notifications"],[data-page="public-pages"],[data-page="approvals"],[data-page="registrations"]').forEach(button=>button.onclick=()=>navigate(button.dataset.page));

document.getElementById('appMain').insertAdjacentHTML('beforeend',`
<section class="page" id="page-profile"><div class="page-head"><div><p class="eyebrow">ACCOUNT & ORGANIZATION</p><h1>My Profile & Company</h1><p>Manage your account, verification, company relationship, documents, and access.</p></div><span class="page-access-badge">Account page complete</span></div><div id="profilePageContent"></div></section>
<section class="page" id="page-notifications"><div class="page-head"><div><p class="eyebrow">COMMUNICATION CENTER</p><h1>Notification Center</h1><p>Review financial news, campaign updates, event invitations, and membership notices.</p></div><button class="secondary" id="markNotificationsRead">✓ Mark all as read</button></div><div id="notificationPageContent"></div></section>
<section class="page" id="page-public-pages"><div class="page-head"><div><p class="eyebrow">ADMIN CONTENT CONTROL</p><h1>All Page Management</h1><p>Admin can edit/update every related website, app, content and admin page with required notes and audit trail.</p></div><button class="primary" id="newPublicPage">＋ Add managed page</button></div><div id="publicPagesContent"></div></section>
<section class="page active" id="page-approvals"><div class="page-head"><div><p class="eyebrow">ADMIN GOVERNANCE</p><h1>Approvals & Verification</h1><p>Review company, member, partner, funding, and publication submissions with a complete audit trail.</p></div><button class="secondary" id="approvalAuditExport">Export audit log</button></div><div id="approvalPageContent"></div></section>
<section class="page" id="page-registrations"><div class="page-head"><div><p class="eyebrow">EVENT OPERATIONS</p><h1>Event Registrations</h1><p>Manage public attendees, member invitations, check-in, capacity, and attendance reporting.</p></div><button class="primary" id="exportRegistrations">Export registrations</button></div><div id="registrationPageContent"></div></section>`);

const profileDocuments=[['Company registration certificate','Verified 18 Jun 2026'],['Tax patent / registration','Verified 18 Jun 2026'],['Representative identity & authority','Verified 19 Jun 2026'],['Membership payment','Paid through current period']];
function renderProfilePage(){
  if(!currentMember)return;const isAdmin=currentMember.isAdmin,org=isAdmin?'IDI Association':currentMember.organization,completion=currentMember.verified||isAdmin?100:75;
  document.getElementById('profilePageContent').innerHTML=`<div class="account-layout"><aside class="account-card"><div class="account-identity"><div class="account-avatar">${initials(currentMember.name)}</div><h2>${currentMember.name}</h2><p>${currentMember.role} • ${org}</p><span class="member-tier-chip">${currentMember.tier}</span></div><div class="profile-completion"><div><span>Profile completion</span><strong>${completion}%</strong></div><i><b style="width:${completion}%"></b></i><small>${completion===100?'All requirements completed':'Complete remaining requirements for verification'}</small></div><div class="account-facts"><div><span>Account email</span><strong>${currentMember.email}</strong></div><div><span>Verification</span><strong>${isAdmin||currentMember.verified?'✓ IDI verified':'Under review'}</strong></div><div><span>Membership expiry</span><strong>${currentMember.membershipExpires||'Administrative account'}</strong></div><div><span>Payment status</span><strong>${currentMember.paymentStatus||'Not applicable'}</strong></div></div></aside><article class="account-panel"><div class="account-tabs"><button class="active" data-account-tab="details">Personal details</button><button data-account-tab="company">Company</button><button data-account-tab="documents">Verification documents</button><button data-account-tab="security">Security & access</button></div><div id="accountTabContent"></div></article></div>`;
  document.querySelectorAll('[data-account-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-account-tab]').forEach(item=>item.classList.toggle('active',item===button));renderAccountTab(button.dataset.accountTab)});renderAccountTab('details')
}
function renderAccountTab(tab){
  const host=document.getElementById('accountTabContent'),member=currentMember;if(!host||!member)return;
  if(tab==='details')host.innerHTML=`<form class="profile-section" id="profileDetailsForm"><h3>Personal and contact information</h3><div class="profile-field-grid"><label>Full name<input name="name" value="${member.name}" required></label><label>Role / position<input name="role" value="${member.role}" required></label><label>Email address<input type="email" name="email" value="${member.email}" required></label><label>Phone number<input name="phone" value="+855 12 888 168"></label><label>Preferred language<select name="language"><option>English</option><option>Khmer</option></select></label><label>Time zone<input value="Asia/Phnom Penh" readonly></label></div><div class="modal-actions"><button class="secondary" type="button" id="requestProfileUpdate">Request account update</button><button class="primary" type="submit">Save contact preferences</button></div></form>`;
  if(tab==='company')host.innerHTML=`<div class="profile-section"><h3>Connected organization</h3><div class="member-access-banner"><span>◆</span><div><strong>${member.organization}</strong><p>${member.isAdmin?'Platform operator and association administration':'Verified company relationship • Business directory profile connected'}</p></div><button class="secondary" id="openConnectedCompany">${member.isAdmin?'Open directory':'View company profile'}</button></div><div class="document-checklist"><article><span>✓</span><div><strong>Company information</strong><small>Legal name, category, description and contacts</small></div><em>COMPLETE</em></article><article><span>✓</span><div><strong>Products, services and media</strong><small>Logo, cover, photos, website and social media</small></div><em>COMPLETE</em></article><article><span>🔒</span><div><strong>Verified information locked</strong><small>Changes require an administrator review request</small></div><em>CONTROLLED</em></article></div></div>`;
  if(tab==='documents')host.innerHTML=`<div class="profile-section"><h3>Verification requirements</h3><div class="document-checklist">${profileDocuments.map(doc=>`<article><span>✓</span><div><strong>${doc[0]}</strong><small>${doc[1]}</small></div><em>APPROVED</em></article>`).join('')}</div><div class="modal-actions"><button class="secondary" id="uploadRenewedDocument">Upload renewed document</button><button class="primary" id="requestVerificationReview">Request verification review</button></div></div>`;
  if(tab==='security')host.innerHTML=`<div class="profile-section"><h3>Security and account access</h3><div class="document-checklist"><article><span>🔐</span><div><strong>Password</strong><small>Last changed 32 days ago</small></div><button class="secondary" data-security-action="password">Change</button></article><article><span>◎</span><div><strong>Two-factor authentication</strong><small>Recommended for investment and administration accounts</small></div><button class="secondary" data-security-action="2FA">Enable</button></article><article><span>◷</span><div><strong>Active sessions</strong><small>1 web session • Phnom Penh</small></div><button class="secondary" data-security-action="sessions">Review</button></article><article><span>▤</span><div><strong>Account activity</strong><small>Login and change-request audit history</small></div><button class="secondary" data-security-action="activity">View log</button></article></div></div>`;
  bindAccountTabActions()
}
function bindAccountTabActions(){document.getElementById('profileDetailsForm')?.addEventListener('submit',event=>{event.preventDefault();showToast('Profile preferences saved','Contact and language preferences were updated.')});document.getElementById('requestProfileUpdate')?.addEventListener('click',()=>typeof openMembershipChange==='function'?openMembershipChange(currentMember.email,'request'):showToast('Update request opened','Your request will be reviewed by an administrator.'));document.getElementById('openConnectedCompany')?.addEventListener('click',()=>navigate('directory'));document.getElementById('uploadRenewedDocument')?.addEventListener('click',()=>showToast('Document upload opened','Choose the renewed legal or membership document to submit for review.'));document.getElementById('requestVerificationReview')?.addEventListener('click',()=>showToast('Verification review requested','An administrator will review the completed requirements.'));document.querySelectorAll('[data-security-action]').forEach(button=>button.onclick=()=>showToast(`${button.dataset.securityAction} controls opened`,'Security changes require account verification and are recorded in the audit log.'))}

let notificationRecords=[
  {icon:'▥',title:'Restricted market update available',body:'A new government investment incentive is available for your membership tier.',time:'12 minutes ago',page:'news',unread:true},
  {icon:'◎',title:'Investor match confirmed',body:'Impact Asia Capital requested a meeting regarding a verified company opportunity.',time:'48 minutes ago',page:'pipeline',unread:true},
  {icon:'◷',title:'Private event invitation',body:'You are invited to the Private Investor & Founder Roundtable.',time:'2 hours ago',page:'events',unread:true},
  {icon:'▣',title:'Membership renewal reminder',body:'Your membership renewal date is approaching. Review the invoice and payment options.',time:'Yesterday',page:'billing',unread:true},
  {icon:'◉',title:'Campaign application moved to shortlist',body:'Your application was advanced to the shortlist review stage.',time:'2 days ago',page:'campaigns',unread:false},
  {icon:'✓',title:'Company profile verified',body:'All requirements were approved and the blue verification tick is now active.',time:'4 days ago',page:'directory',unread:false}
];
function renderNotificationPage(){const unread=notificationRecords.filter(item=>item.unread).length;document.getElementById('notificationNavCount').textContent=unread;document.getElementById('notificationPageContent').innerHTML=`<div class="platform-page-stats"><article><i>♢</i><div><strong>${unread}</strong><span>Unread notifications</span></div></article><article><i>▥</i><div><strong>6</strong><span>Investment updates</span></div></article><article><i>◷</i><div><strong>3</strong><span>Event invitations</span></div></article><article><i>◎</i><div><strong>2</strong><span>Investor matches</span></div></article></div><div class="notification-layout"><article class="notification-feed"><div class="notification-toolbar"><h2>All notifications</h2><select id="notificationFilter"><option value="all">All types</option><option value="unread">Unread only</option><option value="news">Financial news</option><option value="events">Events</option></select></div><div class="notification-list" id="notificationList"></div></article><aside class="notification-preferences"><h2>Delivery preferences</h2>${[['In-app notifications',true],['Email notifications',true],['VIP SMS alerts',currentMember?.tier==='VIP'||currentMember?.isAdmin],['Event reminders',true],['Membership reminders',true],['Weekly ecosystem digest',false]].map(item=>`<div class="preference-row"><div><strong>${item[0]}</strong><small>Manage this notification channel</small></div><label class="mini-switch"><input type="checkbox" ${item[1]?'checked':''}><span></span></label></div>`).join('')}<div class="modal-actions"><button class="primary" id="saveNotificationPreferences">Save preferences</button></div></aside></div>`;renderNotificationList('all');document.getElementById('notificationFilter').onchange=event=>renderNotificationList(event.target.value);document.getElementById('saveNotificationPreferences').onclick=()=>showToast('Notification preferences saved','Your selected channels and reminder options were updated.')}
function renderNotificationList(filter){const rows=notificationRecords.filter(item=>filter==='all'||filter==='unread'&&item.unread||filter==='news'&&item.page==='news'||filter==='events'&&item.page==='events');document.getElementById('notificationList').innerHTML=rows.map((item,index)=>`<article class="notification-item ${item.unread?'unread':''}"><i>${item.icon}</i><div><strong>${item.title}</strong><p>${item.body}</p><small>${item.time}</small></div><button class="secondary" data-notification-open="${notificationRecords.indexOf(item)}">Open</button></article>`).join('')||'<div class="page-complete-note"><span>✓</span><strong>No notifications match this filter.</strong></div>';document.querySelectorAll('[data-notification-open]').forEach(button=>button.onclick=()=>{const item=notificationRecords[Number(button.dataset.notificationOpen)];item.unread=false;renderNotificationPage();navigate(item.page)})}
document.getElementById('markNotificationsRead').onclick=()=>{notificationRecords.forEach(item=>item.unread=false);renderNotificationPage();showToast('Notifications cleared','All notifications are now marked as read.')};

const defaultManagementProfiles=[
  {name:'Chairman of IDI',position:'Chairman',office:'Board Leadership',expertise:['Investment Policy','Institutional Relations','Strategic Direction'],bio:'Provides board-level direction, institutional credibility, and long-term vision for the IDI investment ecosystem.',photo:'assets/management/chairman.svg'},
  {name:'Vice Chairman',position:'Vice Chairman',office:'Board Leadership',expertise:['Member Development','Governance','Partnerships'],bio:'Supports governance, membership development, and coordination with public and private sector stakeholders.',photo:'assets/management/vice-chairman.svg'},
  {name:'Secretary General',position:'Secretary General',office:'Executive Office',expertise:['Association Management','Compliance','Operations'],bio:'Leads daily association administration, board communication, verification governance, and member service operations.',photo:'assets/management/secretary-general.svg'},
  {name:'Investment Director',position:'Director of Investment Facilitation',office:'Investment Office',expertise:['Fundraising','Investor Matching','Due Diligence'],bio:'Coordinates funders, venture capital partners, pitching programs, funding requests, and investor-company matching.',photo:'assets/management/investment-director.svg'},
  {name:'Membership Director',position:'Director of Membership & Verification',office:'Membership Office',expertise:['Member Services','Verification','Renewal'],bio:'Oversees membership subscription, company verification, blue tick approval, renewal notices, and member update requests.',photo:'assets/management/membership-director.svg'},
  {name:'Strategic Partnership Director',position:'Director of Strategic Partnerships',office:'Partner Office',expertise:['VC Relations','Campaigns','Market Access'],bio:'Manages venture capital partners, strategic partners, campaign creation, invitations, and ecosystem collaboration.',photo:'assets/management/partnership-director.svg'},
  {name:'Digital Platform Manager',position:'Digital Operations Manager',office:'Digital Operations',expertise:['CMS','Analytics','Business Mapping'],bio:'Maintains IDI APP content, admin CMS, business mapping, analytics, notifications, and platform quality control.',photo:'assets/management/digital-manager.svg'},
  {name:'Events & Communications Manager',position:'Events & Communications Manager',office:'Communications Office',expertise:['Events','Financial News','Public Relations'],bio:'Coordinates public/private events, activities calendar, financial news publishing, invitations, and communication reports.',photo:'assets/management/events-manager.svg'}
];
function managementProfiles(){const saved=JSON.parse(localStorage.getItem('idi-management-profiles')||'null');return (saved&&saved.length?saved:defaultManagementProfiles).map((profile,index)=>({...profile,photo:(!profile.photo||profile.photo==='assets/idi-logo.jpg')?defaultManagementProfiles[index]?.photo||'assets/management/chairman.svg':profile.photo}))}
function renderManagementProfiles(){
  const host=document.getElementById('managementDirectoryGrid');if(!host)return;
  host.innerHTML=managementProfiles().map(profile=>`<article class="management-person-card"><div class="management-person-photo">${profile.photo?`<img src="${cmsFieldValue(profile.photo)}" alt="${cmsFieldValue(profile.name)} photo">`:`<span>${profile.name.split(' ').map(word=>word[0]).join('').slice(0,2)}</span>`}</div><div class="management-person-body"><small>${cmsFieldValue(profile.office)}</small><h3>${cmsFieldValue(profile.name)}</h3><span>${cmsFieldValue(profile.position)}</span><p>${cmsFieldValue(profile.bio)}</p><div class="management-expertise">${profile.expertise.map(item=>`<b>${cmsFieldValue(item)}</b>`).join('')}</div></div></article>`).join('')
}

const publicPageRecords=[
  ['Homepage','#landingPage','Hero, hot news, events, running text, ecosystem stats','Published','Website Administrator','Today 10:24','Public website','Admin + Content Editor'],
  ['Management Profile','#management-profile','Full IDI management directory with photo, position, expertise, office, biography and role content','Published','Website Administrator','Today 10:41','Public website','Admin'],
  ['Chairman Speech','#chairman-speech','Chairman message, quote, signature and association vision','Published','Website Administrator','Today 10:42','Public website','Admin'],
  ['Contact Us','#contact-us','Contact information, inquiry form, support channels and submitted inquiries','Published','Website Administrator','Today 10:58','Public website','Admin + Support'],
  ['Business Directory','#public-directory','Featured businesses, company profiles, logos, products, filters and views','Published','Directory Reviewer','Yesterday','Public + member directory','Admin + Directory Reviewer'],
  ['Business Mapping','business-mapping','Google Map pins, country/city/category filters and member-only map access','Published','Directory Reviewer','Yesterday','Member app page','Admin + Directory Reviewer'],
  ['VC & Strategic Partners','#public-partners','Partner logos, mandates, campaign access and organization profiles','Published','Content Editor','Yesterday','Public website','Admin + Partner Manager'],
  ['Financial News','#public-news','Hot/latest news, thumbnails, gallery, publish audience, delivery and read reports','Published','Content Editor','Yesterday','Public + member news','Admin + News Publisher'],
  ['Events & Activities','#public-events','Public/private events, invitation settings, registration and calendar activity','Published','Events Manager','Yesterday','Public + member events','Admin + Events Manager'],
  ['Membership','#memberships','Membership plans, renewal notices, payment, upgrade/downgrade requests','Published','Membership Manager','2 days ago','Public + member billing','Admin + Membership Manager'],
  ['Member Registration','member-registration','Individual/company sign-up, verification documents and membership payment status','Published','Membership Manager','2 days ago','Public onboarding','Admin + Membership Manager'],
  ['Company Registration','company-registration','Company directory submission, logo, cover, products/services and admin verification','Published','Directory Reviewer','2 days ago','Public onboarding','Admin + Directory Reviewer'],
  ['Funding Request','funding','Premium/VIP-only funding application, readiness review and investor flow','Published','Investment Team','2 days ago','Member app page','Admin + Investment Team'],
  ['Campaigns','campaigns','VC/Strategic Partner campaign creation, applications, shortlist and reporting','Published','Partner Manager','2 days ago','Partner app page','Admin + Partner Manager'],
  ['My Account','profile','Member profile, company relationship, documents and update requests','Published','System Administrator','3 days ago','Member app page','Admin + Member Owner'],
  ['Notification Center','notifications','In-app, email, SMS and membership renewal notification preferences','Published','System Administrator','3 days ago','Member app page','Admin + System'],
  ['Approvals & Verification','approvals','Admin verification queues, blue tick approval and decision audit notes','Published','Compliance Admin','3 days ago','Admin page','Admin only'],
  ['Event Registrations','registrations','Public attendee/member invitation list, check-in and attendance reporting','Published','Events Manager','3 days ago','Admin page','Admin + Events Manager'],
  ['DP-IED Internal Directory','dp-ied','Digital Platform for Informal Economy Development internal-only connection','Internal only','Website Administrator','3 days ago','Admin page','Admin only']
];
function renderPublicPagesAdmin(){
  const host=document.getElementById('publicPagesContent');if(!host)return;
  const inquiries=JSON.parse(localStorage.getItem('idi-contact-inquiries')||'[]');
  host.innerHTML=`<div class="platform-page-stats"><article><i>▧</i><div><strong>${publicPageRecords.length}</strong><span>Managed pages/modules</span></div></article><article><i>✓</i><div><strong>${publicPageRecords.filter(row=>row[3]==='Published').length}</strong><span>Published pages</span></div></article><article><i>◷</i><div><strong>9</strong><span>Content owners</span></div></article><article><i>✉</i><div><strong>${inquiries.length}</strong><span>Contact inquiries</span></div></article></div><div class="managed-page-toolbar"><button class="active" data-managed-filter="all">All related pages</button><button data-managed-filter="Public website">Public website</button><button data-managed-filter="Member app page">Member app</button><button data-managed-filter="Admin page">Admin only</button><button data-managed-filter="Public onboarding">Registration</button></div><div class="public-page-admin-layout"><article class="public-page-admin-list" id="managedPageList"></article><aside class="public-page-admin-editor"><h2>Professional CMS control</h2><p>Click Edit / update to open a CMS popup form with the previous page data already filled in. Admin must record an update note before publishing changes.</p><div class="document-checklist"><article><span>✓</span><div><strong>Pre-filled page data</strong><small>Title, route, section type, owner, role and content summary</small></div><em>READY</em></article><article><span>✓</span><div><strong>Version control</strong><small>Keep previous content before publishing</small></div><em>ACTIVE</em></article><article><span>✓</span><div><strong>Role permission</strong><small>Only assigned admin roles can publish sensitive pages</small></div><em>REQUIRED</em></article><article><span>✓</span><div><strong>Admin audit log</strong><small>Record staff, time, note and page section</small></div><em>REQUIRED</em></article><article><span>✓</span><div><strong>Responsive preview</strong><small>Review web, responsive, and app view before publishing</small></div><em>REQUIRED</em></article></div>${inquiries.length?`<div class="contact-inquiry-admin"><h3>Latest contact inquiries</h3>${inquiries.slice(0,3).map(item=>`<article><strong>${item.name||'Website visitor'}</strong><small>${item.type||'General inquiry'} • ${item.email||'No email'} • ${new Date(item.submittedAt).toLocaleDateString()}</small><p>${item.message||'No message added.'}</p></article>`).join('')}</div>`:`<div class="contact-inquiry-admin"><h3>Latest contact inquiries</h3><p>No contact inquiry submitted yet.</p></div>`}</aside></div>`;
  const renderManagedList=(filter='all')=>{const rows=publicPageRecords.filter(row=>filter==='all'||row[6]===filter||row[6]?.includes(filter));document.getElementById('managedPageList').innerHTML=rows.map((row,index)=>`<div class="public-page-admin-card"><div><span>${row[1]}</span><h3>${row[0]}</h3><p>${row[2]}</p><small>Last updated by ${row[4]} • ${row[5]}</small><div class="managed-page-meta"><em>${row[6]}</em><em>${row[7]}</em></div></div><b class="${row[3]==='Internal only'?'internal':''}">${row[3]}</b><div class="public-page-actions"><button class="secondary" data-preview-public-page="${row[1]}">Preview</button><button class="primary" data-edit-public-page="${publicPageRecords.indexOf(row)}">Edit / update</button></div></div>`).join('')||'<div class="public-page-admin-empty">No page/module matches this filter.</div>';bindManagedPageButtons()};
  const bindManagedPageButtons=()=>{document.querySelectorAll('[data-preview-public-page]').forEach(button=>button.onclick=()=>{const target=button.dataset.previewPublicPage;if(target.startsWith('#')){document.getElementById('landingPage').style.display='block';document.querySelectorAll('.app-shell').forEach(el=>el.classList.remove('authenticated'));document.querySelector(target)?.scrollIntoView({behavior:'smooth',block:'start'})}else if(document.getElementById(`page-${target}`)){document.getElementById('landingPage').style.display='none';document.querySelectorAll('.app-shell').forEach(el=>el.classList.add('authenticated'));navigate(target)}else{showToast('Open app page',`This module is tracked by admin content control and will connect to the ${target} page in production.`)}});document.querySelectorAll('[data-edit-public-page]').forEach(button=>button.onclick=()=>openManagedPageCms(Number(button.dataset.editPublicPage)))};
  renderManagedList();
  document.querySelectorAll('[data-managed-filter]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-managed-filter]').forEach(item=>item.classList.toggle('active',item===button));renderManagedList(button.dataset.managedFilter)});
}

function cmsFieldValue(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function ensureManagedPageCmsModal(){
  if(document.getElementById('managedPageCmsModal'))return;
  document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="managedPageCmsModal" aria-hidden="true"><div class="modal managed-page-cms-modal"><button class="modal-close" data-managed-cms-close>×</button><header class="cms-modal-header"><small>IDI APP ADMIN CMS</small><h2>Edit page / module content</h2><p>Review the previous data, update content fields, and save with an administrator note.</p></header><form id="managedPageCmsForm"><input type="hidden" name="index"><section class="cms-previous-data"><span>Previous saved data</span><div id="cmsPreviousData"></div></section><section class="management-cms-panel" id="managementCmsPanel" hidden><div class="cms-subhead"><strong>Management directory records</strong><p>Edit leadership photos, positions, expertise and profile summaries shown on the homepage.</p></div><div id="managementCmsRows"></div></section><div class="cms-form-grid"><label>Page / module title<input name="title" required></label><label>Route / anchor<input name="route" required></label><label>Status<select name="status"><option>Published</option><option>Draft</option><option>Internal only</option><option>Needs review</option></select></label><label>Page type<select name="type"><option>Public website</option><option>Public + member directory</option><option>Public + member news</option><option>Public + member events</option><option>Public + member billing</option><option>Public onboarding</option><option>Member app page</option><option>Partner app page</option><option>Admin page</option></select></label><label>Content owner<input name="owner" required></label><label>Allowed admin role<input name="role" required></label></div><label>Content summary / CMS body<textarea name="summary" required></textarea></label><label>Update note / reason <textarea name="note" required placeholder="Required: explain what changed and why, for audit log"></textarea></label><div class="cms-publish-row"><label class="registration-consent"><input type="checkbox" name="responsiveCheck" required> I checked the page for web, responsive, and app view.</label><label class="registration-consent"><input type="checkbox" name="approvalCheck" required> I confirm this update is authorized by the responsible admin role.</label></div><div class="modal-actions"><button type="button" class="secondary" data-managed-cms-close>Cancel</button><button type="button" class="secondary" id="saveManagedDraft">Save draft</button><button type="submit" class="primary">Publish update</button></div></form></div></div>`);
  document.querySelectorAll('[data-managed-cms-close]').forEach(button=>button.onclick=closeManagedPageCms);
  document.getElementById('managedPageCmsModal').onclick=event=>{if(event.target.id==='managedPageCmsModal')closeManagedPageCms()};
  document.getElementById('saveManagedDraft').onclick=()=>saveManagedPageCms(true);
  document.getElementById('managedPageCmsForm').onsubmit=event=>{event.preventDefault();saveManagedPageCms(false)};
}
function openManagedPageCms(index){
  ensureManagedPageCmsModal();
  const row=publicPageRecords[index];if(!row)return;
  const form=document.getElementById('managedPageCmsForm');
  form.elements.index.value=index;form.elements.title.value=row[0];form.elements.route.value=row[1];form.elements.status.value=row[3];form.elements.type.value=row[6];form.elements.owner.value=row[4];form.elements.role.value=row[7];form.elements.summary.value=row[2];form.elements.note.value='';form.elements.responsiveCheck.checked=false;form.elements.approvalCheck.checked=false;
  document.getElementById('cmsPreviousData').innerHTML=`<article><strong>${cmsFieldValue(row[0])}</strong><p>${cmsFieldValue(row[2])}</p><dl><div><dt>Route</dt><dd>${cmsFieldValue(row[1])}</dd></div><div><dt>Status</dt><dd>${cmsFieldValue(row[3])}</dd></div><div><dt>Owner</dt><dd>${cmsFieldValue(row[4])}</dd></div><div><dt>Last update</dt><dd>${cmsFieldValue(row[5])}</dd></div><div><dt>Type</dt><dd>${cmsFieldValue(row[6])}</dd></div><div><dt>Role</dt><dd>${cmsFieldValue(row[7])}</dd></div></dl></article>`;
  const managementPanel=document.getElementById('managementCmsPanel');managementPanel.hidden=row[0]!=='Management Profile';if(row[0]==='Management Profile')renderManagementCmsRows();
  const modal=document.getElementById('managedPageCmsModal');modal.classList.add('open');modal.setAttribute('aria-hidden','false');form.elements.title.focus()
}
function closeManagedPageCms(){const modal=document.getElementById('managedPageCmsModal');modal?.classList.remove('open');modal?.setAttribute('aria-hidden','true')}
function renderManagementCmsRows(){
  document.getElementById('managementCmsRows').innerHTML=managementProfiles().map((profile,index)=>`<article class="management-cms-row"><div class="management-cms-avatar">${profile.photo?`<img src="${cmsFieldValue(profile.photo)}" alt="">`:`<span>${profile.name.split(' ').map(word=>word[0]).join('').slice(0,2)}</span>`}</div><div class="management-cms-fields"><div class="cms-form-grid"><label>Name<input name="mgmtName${index}" value="${cmsFieldValue(profile.name)}"></label><label>Position<input name="mgmtPosition${index}" value="${cmsFieldValue(profile.position)}"></label><label>Office / committee<input name="mgmtOffice${index}" value="${cmsFieldValue(profile.office)}"></label><label>Photo URL / asset path<input name="mgmtPhoto${index}" value="${cmsFieldValue(profile.photo)}" placeholder="assets/photo-name.jpg"></label></div><label>Expertise / tags<input name="mgmtExpertise${index}" value="${cmsFieldValue(profile.expertise.join(', '))}" placeholder="Investment, Governance, Partnerships"></label><label>Profile summary<textarea name="mgmtBio${index}">${cmsFieldValue(profile.bio)}</textarea></label></div></article>`).join('')
}
function saveManagedPageCms(draft=false){
  const form=document.getElementById('managedPageCmsForm'),index=Number(form.elements.index.value),row=publicPageRecords[index];if(!row)return;
  const note=form.elements.note.value.trim();if(!draft&&(!form.elements.responsiveCheck.checked||!form.elements.approvalCheck.checked)){showToast('CMS checklist required','Please confirm responsive preview and role authorization before publishing.');return}
  if(!note){showToast('Update note required','Please add the reason/note for the CMS audit log.');form.elements.note.focus();return}
  const previous=[...row];row[0]=form.elements.title.value.trim();row[1]=form.elements.route.value.trim();row[2]=form.elements.summary.value.trim();row[3]=draft?'Draft':form.elements.status.value;row[4]=currentMember?.name||form.elements.owner.value.trim();row[5]='Just now';row[6]=form.elements.type.value;row[7]=form.elements.role.value.trim();
  if(previous[0]==='Management Profile'){const updated=managementProfiles().map((profile,profileIndex)=>({name:form.elements[`mgmtName${profileIndex}`]?.value.trim()||profile.name,position:form.elements[`mgmtPosition${profileIndex}`]?.value.trim()||profile.position,office:form.elements[`mgmtOffice${profileIndex}`]?.value.trim()||profile.office,photo:form.elements[`mgmtPhoto${profileIndex}`]?.value.trim()||'',expertise:String(form.elements[`mgmtExpertise${profileIndex}`]?.value||'').split(',').map(item=>item.trim()).filter(Boolean),bio:form.elements[`mgmtBio${profileIndex}`]?.value.trim()||profile.bio}));localStorage.setItem('idi-management-profiles',JSON.stringify(updated));renderManagementProfiles()}
  const audit=JSON.parse(localStorage.getItem('idi-managed-page-audit')||'[]');audit.unshift({page:row[0],previousTitle:previous[0],previousSummary:previous[2],status:row[3],note,staff:currentMember?.name||'Website Administrator',savedAt:new Date().toISOString(),draft});localStorage.setItem('idi-managed-page-audit',JSON.stringify(audit));
  closeManagedPageCms();renderPublicPagesAdmin();showToast(draft?'CMS draft saved':'CMS page updated',`${row[0]} saved with previous data, update note and audit log.`)
}

const approvalQueues={company:[['Kampuchea Solar Solutions','Company verification','Registration, tax patent and representative identity submitted.'],['Lotus Food Processing','Company verification','Profile, logo, products and operating license completed.'],['Phnom Digital Commerce','Company verification','Payment confirmed; final administrator approval required.']],member:[['Sovannary Heng','VIP membership','Payment received and company relationship confirmed.'],['Borey Chan','Premium membership','Identity and contact verification completed.']],partner:[['ASEAN Green Fund','Venture capital partner','Mandate, investment thesis and authorized representative submitted.']],funding:[['Mekong AgriTech','Funding request','Financial model, pitch deck and use of funds submitted.'],['Sabay Logistics','Funding request','Funding readiness score 84; compliance review completed.']],news:[['Cambodia Green Investment Incentive','News publication','Source verified; audience selected as VIP and Premium.']]};
let activeApprovalQueue='company';
function renderApprovalPage(){const total=Object.values(approvalQueues).flat().length;document.getElementById('approvalPageContent').innerHTML=`<div class="platform-page-stats"><article><i>◫</i><div><strong>${approvalQueues.company.length}</strong><span>Company reviews</span></div></article><article><i>♙</i><div><strong>${approvalQueues.member.length}</strong><span>Member reviews</span></div></article><article><i>◎</i><div><strong>${approvalQueues.partner.length}</strong><span>Partner reviews</span></div></article><article><i>✓</i><div><strong>${total}</strong><span>Total pending</span></div></article></div><div class="approval-board"><article><div class="queue-tabs">${Object.keys(approvalQueues).map(key=>`<button data-approval-queue="${key}" class="${key===activeApprovalQueue?'active':''}">${key[0].toUpperCase()+key.slice(1)} <b>${approvalQueues[key].length}</b></button>`).join('')}</div><div class="approval-list" id="approvalList"></div></article><aside class="approval-guide"><h2>Review standard</h2><p>Every approval must be evidence-based, role-controlled, and recorded with an administrator note.</p><ol><li>Confirm identity and authority</li><li>Check required documents</li><li>Verify payment where applicable</li><li>Review conflicts and risk flags</li><li>Record decision and reason</li></ol><small>All actions create a timestamped audit entry showing the responsible staff account.</small></aside></div>`;renderApprovalList();document.querySelectorAll('[data-approval-queue]').forEach(button=>button.onclick=()=>{activeApprovalQueue=button.dataset.approvalQueue;renderApprovalPage()})}
function renderApprovalList(){document.getElementById('approvalList').innerHTML=approvalQueues[activeApprovalQueue].map((item,index)=>`<article class="approval-card"><header><div><h3>${item[0]}</h3><p>${item[1]} • Submitted ${index+1} day${index?'s':''} ago</p></div><span class="approval-status">PENDING REVIEW</span></header><p>${item[2]}</p><div class="approval-evidence"><span>✓ Identity checked</span><span>✓ Documents uploaded</span><span>▤ Audit log ready</span></div><label>Administrator note<textarea data-approval-note="${index}" placeholder="Required decision reason"></textarea></label><div class="approval-actions"><button class="primary" data-approval-action="approve:${index}">Approve & verify</button><button class="secondary" data-approval-action="request:${index}">Request information</button><button class="text-btn" data-approval-action="reject:${index}">Reject</button></div></article>`).join('')||'<div class="page-complete-note"><span>✓</span><strong>This approval queue is complete.</strong></div>';document.querySelectorAll('[data-approval-action]').forEach(button=>button.onclick=()=>{const [action,index]=button.dataset.approvalAction.split(':'),note=document.querySelector(`[data-approval-note="${index}"]`).value.trim();if(!note){showToast('Administrator note required','Add a decision reason before completing this review.');return}const record=approvalQueues[activeApprovalQueue].splice(Number(index),1)[0];renderApprovalPage();showToast(action==='approve'?'Approved and verified':action==='request'?'Information requested':'Submission rejected',`${record[0]} • Decision and administrator note added to the audit log.`)})}
document.getElementById('approvalAuditExport').onclick=()=>showToast('Audit log prepared','Approval decisions, notes, staff users, and timestamps are ready for export.');

const seededRegistrations=[['Sokha Kim','sokha@uniholding.com','UNI Holding','VIP','Checked in'],['Maly Sok','maly@mekongagri.com','Mekong AgriTech','Premium','Registered'],['Dara Lim','dara@sabaylogistics.com','Sabay Logistics','Standard','Registered'],['Rina Chen','rina@impactasia.vc','Impact Asia Capital','Investor','Checked in'],['Chenda Pov','chenda@gmail.com','Independent','Public guest','Registered'],['Vireak S.','vireak@ballangk.com','Ballangk Mall','Partner','Registered']];
function getRegistrationRows(){const stored=JSON.parse(localStorage.getItem('uni-public-event-registrations')||'[]').map(item=>[item.name,item.email,item.organization||'Independent',item.attendeeType,item.checkedIn?'Checked in':'Registered']);return [...stored,...seededRegistrations]}
function renderRegistrationPage(){const rows=getRegistrationRows(),checked=rows.filter(row=>row[4]==='Checked in').length;document.getElementById('registrationPageContent').innerHTML=`<div class="platform-page-stats"><article><i>◷</i><div><strong>327</strong><span>Total registrations</span></div></article><article><i>✓</i><div><strong>284</strong><span>Confirmed attendees</span></div></article><article><i>◎</i><div><strong>78%</strong><span>Check-in forecast</span></div></article><article><i>＋</i><div><strong>116</strong><span>Seats remaining</span></div></article></div><div class="registration-dashboard"><article class="registration-table-panel"><div class="registration-filters"><select id="registrationEvent"><option>Cambodia Investment Forum 2026</option><option>SME Growth & Investment Pitch</option><option>Private Investor & Founder Roundtable</option></select><input id="registrationSearch" placeholder="Search attendee, email, company"><select id="registrationStatus"><option value="all">All statuses</option><option value="Registered">Registered</option><option value="Checked in">Checked in</option></select></div><table class="registration-table"><thead><tr><th>Attendee</th><th>Organization</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody id="registrationTableBody"></tbody></table></article><aside class="registration-side"><h2>Attendance overview</h2><div class="attendance-ring"><div><strong>78%</strong><span>FORECAST</span></div></div><div class="registration-breakdown"><div><span>VIP members</span><strong>64</strong></div><div><span>Premium members</span><strong>88</strong></div><div><span>Standard members</span><strong>72</strong></div><div><span>Public guests</span><strong>60</strong></div><div><span>Checked in now</span><strong>${checked}</strong></div></div><div class="modal-actions"><button class="primary" id="openEventCheckin">Open check-in mode</button></div></aside></div>`;renderRegistrationTable();document.getElementById('registrationSearch').oninput=renderRegistrationTable;document.getElementById('registrationStatus').onchange=renderRegistrationTable;document.getElementById('openEventCheckin').onclick=()=>showToast('Check-in mode ready','Scan tickets or search attendees to record arrival and attendance time.')}
function renderRegistrationTable(){const query=(document.getElementById('registrationSearch')?.value||'').toLowerCase(),status=document.getElementById('registrationStatus')?.value||'all';const rows=getRegistrationRows().filter(row=>(!query||row.join(' ').toLowerCase().includes(query))&&(status==='all'||row[4]===status));document.getElementById('registrationTableBody').innerHTML=rows.map((row,index)=>`<tr><td><strong>${row[0]}</strong><small>${row[1]}</small></td><td>${row[2]}</td><td>${row[3]}</td><td><span class="checkin-chip ${row[4]==='Checked in'?'checked':''}">${row[4]}</span></td><td><button class="secondary" data-checkin-row="${index}">${row[4]==='Checked in'?'View':'Check in'}</button></td></tr>`).join('');document.querySelectorAll('[data-checkin-row]').forEach(button=>button.onclick=()=>{button.textContent='View';const chip=button.closest('tr').querySelector('.checkin-chip');chip.textContent='Checked in';chip.classList.add('checked');showToast('Attendance recorded','Check-in time and responsible staff user were added to the event log.')})}
document.getElementById('exportRegistrations').onclick=()=>showToast('Registration report prepared','Attendees, invitation source, check-in status, and attendance metrics are ready to export.');

document.getElementById('notificationButton').onclick=()=>{renderNotificationPage();navigate('notifications')};
const platformPagesLogin=loginAs;loginAs=function(key){platformPagesLogin(key);renderProfilePage();renderNotificationPage();if(currentMember?.isAdmin){renderPublicPagesAdmin();renderApprovalPage();renderRegistrationPage()}completeNavigationForProfile()};
renderManagementProfiles();
renderProfilePage();renderNotificationPage();if(currentMember?.isAdmin){renderPublicPagesAdmin();renderApprovalPage();renderRegistrationPage()}completeNavigationForProfile();
